### ISSUE TITLE
Make Silver available in a repo somewhere

### ISSUE THREAD

**Issue by emmby** [johncarl81/silver#1]
oss.sonatype.org https://docs.sonatype.org/display/Repository/Sonatype+OSS+Maven+Repository+Usage+Guide  would be great, but if that's too much overhead, a quick fix is to do something like http://stackoverflow.com/questions/14013644/hosting-a-maven-repository-on-github

**Comment by johncarl81** [comment]
Will do.

Personally, I'm mulling over the name of the library and a couple other issues that would need to be resolved before an initial release.

Are you looking to use Silver in Roboguice?

**Comment by emmby** [comment]
Yeah. Still experimenting, but looking at using it to help speed up startup
class scanning

**Comment by johncarl81** [comment]
Cool.

One thing that comes to mind and may be relevant is to make an annotation processor that would do what Gin (https://code.google.com/p/google-gin/) does with GWT.  Gin uses Guice, but uses a GWT Generator that provides a bunch of pre-generated bindings (from my limited understanding) that speed up startup and discovery throughout Guice running on GWT.  If you could accomplish that, it may not only help startup time with Roboguice but Guice as well.

Let me know if you need anything of course.

**Comment by johncarl81** [comment]
Hmm, I think Im not going to officially publish this one.  If a maven dependency is needed, you can use jitpack to reference a commit directly:

https://jitpack.io/#johncarl81/silver/281de9d526
