### ISSUE TITLE
Is Silver android-specific?

### ISSUE THREAD

**Issue by emmby** [johncarl81/silver#2]
I started trying to use it for a project, but I get the following error:

[ERROR] org.androidtransfuse.TransfuseAnalysisException: @Silver code generation did not complete successfully.

Is Silver Android-specific?  If so, you may want to update the Readme to indicate that.

**Comment by johncarl81** [comment]
It isn't Android specific, but it uses Transfuse's guts which grew out of the Android specific implementation, that's why you see "android" on the package name.

How did you get this error?
